fix C++ error
cori07::utils(1:01pm) #1199 make sort_file_list.o
  CXX      sort_file_list.o
In file included from /opt/gcc/11.2.0/snos/include/g++/map:60,
                 from sort_file_list.cpp:24:
/opt/gcc/11.2.0/snos/include/g++/bits/stl_tree.h: In instantiation of 'static const _Key& std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_S_key(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Const_Link_type) [with _Key = std::vector<long long int>; _Val = std::pair<const std::vector<long long int>, std::__cxx11::basic_string<char> >; _KeyOfValue = std::_Select1st<std::pair<const std::vector<long long int>, std::__cxx11::basic_string<char> > >; _Compare = compv; _Alloc = std::allocator<std::pair<const std::vector<long long int>, std::__cxx11::basic_string<char> > >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Const_Link_type = const std::_Rb_tree_node<std::pair<const std::vector<long long int>, std::__cxx11::basic_string<char> > >*]':
/opt/gcc/11.2.0/snos/include/g++/bits/stl_tree.h:2433:62:   required from 'std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::iterator std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_emplace_hint_unique(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::const_iterator, _Args&& ...) [with _Args = {const std::piecewise_construct_t&, std::tuple<const std::vector<long long int, std::allocator<long long int> >&>, std::tuple<>}; _Key = std::vector<long long int>; _Val = std::pair<const std::vector<long long int>, std::__cxx11::basic_string<char> >; _KeyOfValue = std::_Select1st<std::pair<const std::vector<long long int>, std::__cxx11::basic_string<char> > >; _Compare = compv; _Alloc = std::allocator<std::pair<const std::vector<long long int>, std::__cxx11::basic_string<char> > >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::iterator = std::_Rb_tree<std::vector<long long int>, std::pair<const std::vector<long long int>, std::__cxx11::basic_string<char> >, std::_Select1st<std::pair<const std::vector<long long int>, std::__cxx11::basic_string<char> > >, compv, std::allocator<std::pair<const std::vector<long long int>, std::__cxx11::basic_string<char> > > >::iterator; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::const_iterator = std::_Rb_tree<std::vector<long long int>, std::pair<const std::vector<long long int>, std::__cxx11::basic_string<char> >, std::_Select1st<std::pair<const std::vector<long long int>, std::__cxx11::basic_string<char> > >, compv, std::allocator<std::pair<const std::vector<long long int>, std::__cxx11::basic_string<char> > > >::const_iterator]'
/opt/gcc/11.2.0/snos/include/g++/bits/stl_map.h:501:37:   required from 'std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](const key_type&) [with _Key = std::vector<long long int>; _Tp = std::__cxx11::basic_string<char>; _Compare = compv; _Alloc = std::allocator<std::pair<const std::vector<long long int>, std::__cxx11::basic_string<char> > >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = std::__cxx11::basic_string<char>; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = std::vector<long long int>]'
sort_file_list.cpp:378:40:   required from here
/opt/gcc/11.2.0/snos/include/g++/bits/stl_tree.h:770:15: error: static assertion failed: comparison object must be invocable as const
  770 |               is_invocable_v<const _Compare&, const _Key&, const _Key&>,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/gcc/11.2.0/snos/include/g++/bits/stl_tree.h:770:15: note: 'std::is_invocable_v<const compv&, const std::vector<long long int, std::allocator<long long int> >&, const std::vector<long long int, std::allocator<long long int> >&>' evaluates to false
make: *** [Makefile:493: sort_file_list.o] Error 1